import { expect, test } from "@playwright/test";
import { importAssetsAndEnterPlayableShell } from "./helpers/phase8-import";
function parseMetric(raw, label) {
    const match = raw.match(new RegExp(`^${label}:\\s*(-?\\d+)$`));
    if (!match) {
        throw new Error(`Unable to parse ${label} metric from: ${raw}`);
    }
    return Number(match[1]);
}
test("phase 7 app shell smoke flow: load, interact, pause, step, resume", async ({ page }) => {
    await importAssetsAndEnterPlayableShell(page);
    await expect(page.getByTestId("hospital-canvas-summary")).toContainText("patients 0");
    await page.keyboard.press("KeyQ");
    await expect(page.getByTestId("hospital-placement-mode")).toHaveText("Placement: none");
    await expect(page.getByTestId("hospital-canvas-summary")).toContainText("patients 0");
    await expectCanvasAlpha(page, "hospital-map-canvas");
    await expect(page.getByTestId("hospital-map-select")).toHaveValue("LEVELS/EXAMPLE.MAP");
    await page.getByTestId("playfield").focus();
    await page.keyboard.press("F4");
    await expect(page.getByTestId("town-map-panel")).toBeVisible();
    await expect(page.locator(":focus")).toHaveAttribute("data-testid", "town-map-panel-select");
    await expect(page.getByTestId("town-map-panel-current")).toHaveText("Map: LEVELS/EXAMPLE.MAP");
    await expect(page.getByTestId("town-map-panel-campaign")).toContainText("Campaign:");
    await expect(page.getByTestId("town-map-panel-objective")).toContainText("Level status:");
    await expect(page.getByTestId("town-map-panel-cash")).toHaveText(await page.getByTestId("cash").textContent() ?? "");
    await expect(page.getByTestId("town-map-panel-land")).toContainText("Land:");
    await expect(page.getByTestId("town-map-panel-details")).toContainText("Map details:");
    await page.getByTestId("town-map-panel-select").selectOption("LEVELS/SECOND.MAP");
    await expect(page.getByTestId("hospital-map-select")).toHaveValue("LEVELS/SECOND.MAP");
    await expect(page.getByTestId("hospital-canvas-summary")).toContainText("LEVELS/SECOND.MAP");
    await expect(page.getByTestId("town-map-panel-current")).toHaveText("Map: LEVELS/SECOND.MAP");
    await page.getByTestId("town-map-panel-close").click();
    await expect(page.getByTestId("town-map-panel")).toBeHidden();
    await page.getByTestId("hospital-camera-east").click();
    await expect(page.getByTestId("hospital-canvas-summary")).toContainText("viewport 76,75");
    await page.keyboard.press("ArrowDown");
    await expect(page.getByTestId("hospital-canvas-summary")).toContainText("viewport 76,79");
    await page.getByTestId("save-game").click();
    await expect(page.getByTestId("save-status")).toContainText("Save: tick");
    await page.getByTestId("hospital-map-select").selectOption("LEVELS/EXAMPLE.MAP");
    await expect(page.getByTestId("hospital-canvas-summary")).toContainText("LEVELS/EXAMPLE.MAP");
    await page.getByTestId("load-game").click();
    await expect(page.getByTestId("save-status")).toContainText("Save: loaded tick");
    await expect(page.getByTestId("hospital-map-select")).toHaveValue("LEVELS/SECOND.MAP");
    await expect(page.getByTestId("hospital-canvas-summary")).toContainText("LEVELS/SECOND.MAP");
    await page.keyboard.press("KeyF");
    await expect(page.getByTestId("hospital-placement-mode")).toHaveText("Placement: build GP's Office");
    await page.keyboard.press("KeyQ");
    await expect(page.getByTestId("hospital-placement-mode")).toHaveText("Placement: none");
    await page.keyboard.press("KeyF");
    await expect(page.getByTestId("hospital-placement-mode")).toHaveText("Placement: build GP's Office");
    await page.keyboard.press("Escape");
    await expect(page.getByTestId("hospital-placement-mode")).toHaveText("Placement: none");
    await expect(page.getByTestId("game-menu-bar")).toBeHidden();
    await page.keyboard.press("KeyF");
    await expect(page.getByTestId("hospital-placement-mode")).toHaveText("Placement: build GP's Office");
    await expect(page.getByTestId("paused")).toHaveText("Paused: no");
    await page.keyboard.press("Space");
    await expect(page.getByTestId("hospital-placement-mode")).toHaveText("Placement: build GP's Office facing east");
    await expect(page.getByTestId("action-status")).toHaveText("Action: placement rotated east");
    await expect(page.getByTestId("paused")).toHaveText("Paused: no");
    await page.getByTestId("hospital-map-canvas").hover({ position: { x: 384, y: 160 } });
    await expect(page.getByTestId("hospital-placement-mode")).toContainText("facing east at");
    await expect(page.getByTestId("hospital-placement-mode")).toContainText("(valid)");
    await page.keyboard.press("Enter");
    await expect(page.getByTestId("action-status")).toHaveText("Action: room built");
    await expect(page.getByTestId("open-diagnosis-rooms")).toHaveText("Open diagnosis rooms: 2");
    await expect(page.getByTestId("hospital-canvas-summary")).toContainText("rooms 3");
    await page.getByTestId("hospital-map-canvas").click({ position: { x: 384, y: 160 } });
    await expect(page.getByTestId("selection-status")).toContainText("Selection: GP's Office room");
    await page.getByTestId("treatment-room-toggle").click();
    await expect(page.getByTestId("open-diagnosis-rooms")).toHaveText("Open diagnosis rooms: 1");
    await page.getByTestId("treatment-room-toggle").click();
    await expect(page.getByTestId("open-diagnosis-rooms")).toHaveText("Open diagnosis rooms: 2");
    await page.getByTestId("build-treatment-room").click();
    await page.getByTestId("playfield").focus();
    await page.keyboard.press("Enter");
    await expect(page.getByTestId("hospital-placement-mode")).toHaveText("Placement: build Ward");
    await page.getByTestId("hospital-map-canvas").hover({ position: { x: 384, y: 160 } });
    await expect(page.getByTestId("hospital-placement-mode")).toContainText("blocked: occupied");
    await page.keyboard.press("KeyE");
    await expect(page.getByTestId("action-status")).toHaveText("Action: room blocked: occupied");
    await expect(page.getByTestId("open-treatment-rooms")).toHaveText("Open treatment rooms: 1");
    await expect(page.getByTestId("hospital-canvas-summary")).toContainText("rooms 3");
    await page.getByTestId("hire-nurse").click();
    await expect(page.getByTestId("hospital-placement-mode")).toHaveText("Placement: hire Nurse");
    await page.getByTestId("hospital-map-canvas").hover({ position: { x: 416, y: 176 } });
    await expect(page.getByTestId("hospital-placement-mode")).toContainText("(valid)");
    await page.getByTestId("hospital-map-canvas").click({ position: { x: 416, y: 176 } });
    await expect(page.getByTestId("action-status")).toHaveText("Action: staff hired");
    await expect(page.getByTestId("active-staff")).toHaveText("Active staff: 3");
    await expect(page.getByTestId("hospital-canvas-summary")).toContainText("staff 3");
    await page.getByTestId("hospital-map-canvas").click({ position: { x: 416, y: 176 } });
    await expect(page.getByTestId("selection-status")).toContainText("Selection: Nurse");
    await page.getByTestId("staff-break-toggle").click();
    await expect(page.getByTestId("active-staff")).toHaveText("Active staff: 2");
    await expect(page.getByTestId("on-break-staff")).toHaveText("On-break staff: 1");
    await page.getByTestId("staff-break-toggle").click();
    await expect(page.getByTestId("active-staff")).toHaveText("Active staff: 3");
    await expect(page.getByTestId("on-break-staff")).toHaveText("On-break staff: 0");
    await expect(page.getByTestId("seed")).toHaveText("Seed: 1234");
    const tickMetric = page.getByTestId("tick");
    const treatedMetric = page.getByTestId("treated");
    const waitingMetric = page.getByTestId("waiting");
    const pauseToggle = page.getByTestId("pause-toggle");
    await expect
        .poll(async () => parseMetric(await tickMetric.textContent().then((text) => text ?? ""), "Tick"), {
        timeout: 3000
    })
        .toBeGreaterThan(0);
    await page.keyboard.press("KeyZ");
    await expect(page.getByTestId("speed-status")).toHaveText("Speed: 2x");
    await page.keyboard.press("KeyZ");
    await expect(page.getByTestId("speed-status")).toHaveText("Speed: 4x");
    await expect(page.getByTestId("action-status")).toHaveText("Action: speed changed");
    const tickAfterSpeedChange = parseMetric((await tickMetric.textContent()) ?? "", "Tick");
    await expect
        .poll(async () => parseMetric(await tickMetric.textContent().then((text) => text ?? ""), "Tick"), {
        timeout: 3000
    })
        .toBeGreaterThan(tickAfterSpeedChange + 2);
    await pauseToggle.click();
    await expect(page.getByTestId("paused")).toHaveText("Paused: yes");
    const tickAtPause = parseMetric((await tickMetric.textContent()) ?? "", "Tick");
    await page.waitForTimeout(600);
    const tickWhilePaused = parseMetric((await tickMetric.textContent()) ?? "", "Tick");
    expect(tickWhilePaused).toBe(tickAtPause);
    await page.getByTestId("step").click();
    await expect(tickMetric).toHaveText(`Tick: ${tickAtPause + 1}`);
    await page.getByTestId("save-slot-name").fill("slot-clean");
    await page.getByTestId("save-game").click();
    await expect(page.getByTestId("save-status")).toContainText("Save: tick");
    await page.getByTestId("hospital-map-canvas").click({ button: "right", position: { x: 384, y: 160 } });
    await expect(waitingMetric).toHaveText("Waiting: 1");
    await expect(page.getByTestId("hospital-canvas-summary")).toContainText("patients 1");
    await page.getByTestId("save-slot-name").fill("slot-dirty");
    await page.getByTestId("save-game").click();
    await expect(page.getByTestId("save-status")).toContainText("Save: tick");
    await page.getByTestId("refresh-save-slots").click();
    await expect(page.getByTestId("save-status")).toContainText("slots");
    await page.getByTestId("save-slot-select").selectOption("slot-clean");
    await expect(page.getByTestId("save-slot-name")).toHaveValue("slot-clean");
    await page.getByTestId("load-game").click();
    await expect(page.getByTestId("save-status")).toContainText("Save: loaded tick");
    await expect(tickMetric).toHaveText(`Tick: ${tickAtPause + 1}`);
    await expect(waitingMetric).toHaveText("Waiting: 0");
    await page.getByTestId("save-slot-name").fill("slot-dirty");
    await page.getByTestId("load-game").click();
    await expect(page.getByTestId("save-status")).toContainText("Save: loaded tick");
    await expect(waitingMetric).toHaveText("Waiting: 1");
    await page.getByTestId("delete-save-slot").click();
    await expect(page.getByTestId("save-status")).toHaveText("Save: deleted slot-dirty");
    await page.getByTestId("load-game").click();
    await expect(page.getByTestId("save-status")).toHaveText("Save: no slot");
    await page.getByTestId("save-slot-name").fill("slot-clean");
    await page.getByTestId("load-game").click();
    await expect(page.getByTestId("save-status")).toContainText("Save: loaded tick");
    await expect(waitingMetric).toHaveText("Waiting: 0");
    await expect(page.getByTestId("hospital-canvas-summary")).toContainText("rooms 3");
    await expect(page.getByTestId("hospital-canvas-summary")).toContainText("staff 3");
    await page.getByTestId("hospital-map-canvas").click({ button: "right", position: { x: 384, y: 160 } });
    await expect(waitingMetric).toHaveText("Waiting: 1");
    await page.getByTestId("hospital-map-canvas").click({ position: { x: 384, y: 160 } });
    await expect(page.getByTestId("selection-status")).toContainText("Selection: patient");
    await page.getByTestId("treat").click();
    await expect(waitingMetric).toHaveText("Waiting: 0");
    await expect(treatedMetric).toHaveText("Treated: 1");
    await page.getByTestId("hospital-map-canvas").click({ position: { x: 384, y: 160 } });
    await expect(page.getByTestId("selection-status")).toContainText("Selection: GP's Office room");
    await page.getByTestId("sell-selected-room").click();
    await expect(page.getByTestId("action-status")).toHaveText("Action: room sold");
    await expect(page.getByTestId("hospital-canvas-summary")).toContainText("rooms 2");
    await page.getByTestId("hospital-map-canvas").click({ position: { x: 416, y: 176 } });
    await expect(page.getByTestId("selection-status")).toContainText("Selection: Nurse");
    await page.getByTestId("fire-selected-staff").click();
    await expect(page.getByTestId("action-status")).toHaveText("Action: staff fired");
    await expect(page.getByTestId("hospital-canvas-summary")).toContainText("staff 2");
    const hashText = (await page.getByTestId("hash").textContent()) ?? "";
    expect(hashText).toMatch(/^State hash: [a-f0-9]{8}$/);
    await pauseToggle.click();
    await expect(page.getByTestId("paused")).toHaveText("Paused: no");
    await expect
        .poll(async () => parseMetric(await tickMetric.textContent().then((text) => text ?? ""), "Tick"), {
        timeout: 3000
    })
        .toBeGreaterThan(tickAtPause + 1);
});
test("phase 7 audio flow: gesture-safe init and no Chromium autoplay policy violations", async ({ page }) => {
    const autoplayViolations = [];
    page.on("console", (message) => {
        const text = message.text();
        if (/AudioContext was not allowed to start/i.test(text) || /autoplay/i.test(text)) {
            autoplayViolations.push(text);
        }
    });
    await importAssetsAndEnterPlayableShell(page);
    await expect(page.getByTestId("audio-status")).toHaveText("Audio: waiting-for-user-gesture");
    await page.getByTestId("admit").click();
    await expect(page.getByTestId("audio-status")).toHaveText("Audio: running");
    await expect(page.getByTestId("audio-volume-metric")).toHaveText("Audio volume: 100% (sound on, music on)");
    await page.getByTestId("playfield").focus();
    await page.keyboard.press("Alt+KeyS");
    await expect(page.getByTestId("audio-volume-metric")).toHaveText("Audio volume: 100% (sound off, music on)");
    await page.keyboard.press("Alt+KeyM");
    await expect(page.getByTestId("audio-volume-metric")).toHaveText("Audio volume: 100% (sound off, music off)");
    await page.keyboard.press("Alt+KeyS");
    await expect(page.getByTestId("audio-volume-metric")).toHaveText("Audio volume: 100% (sound on, music off)");
    await page.keyboard.press("Alt+KeyM");
    await expect(page.getByTestId("audio-volume-metric")).toHaveText("Audio volume: 100% (sound on, music on)");
    await page.getByTestId("playfield").focus();
    const audioVolumeBeforeJukebox = (await page.getByTestId("audio-volume-metric").textContent()) ?? "";
    await page.keyboard.press("KeyJ");
    await expect(page.locator(":focus")).toHaveAttribute("data-testid", "audio-volume");
    await expect(page.getByTestId("audio-volume-metric")).toHaveText(audioVolumeBeforeJukebox);
    await expect(page.getByTestId("action-status")).toHaveText("Action: jukebox opened");
    await expect.poll(() => autoplayViolations).toEqual([]);
});
test("phase 7 keyboard shortcuts set original speed tiers", async ({ page }) => {
    await importAssetsAndEnterPlayableShell(page);
    await page.getByTestId("pause-toggle").click();
    await page.getByTestId("playfield").focus();
    await page.keyboard.press("Digit1");
    await expect(page.getByTestId("speed-status")).toHaveText("Speed: 0.5x");
    await expect(page.getByTestId("speed-select")).toHaveValue("0.5");
    await page.keyboard.press("Digit2");
    await expect(page.getByTestId("speed-status")).toHaveText("Speed: 1x");
    await page.keyboard.press("Digit3");
    await expect(page.getByTestId("speed-status")).toHaveText("Speed: 2x");
    await page.keyboard.press("Digit4");
    await expect(page.getByTestId("speed-status")).toHaveText("Speed: 4x");
    await page.keyboard.press("Digit5");
    await expect(page.getByTestId("speed-status")).toHaveText("Speed: 8x");
    await expect(page.getByTestId("action-status")).toHaveText("Action: speed changed");
});
test("phase 7 keyboard shortcuts zoom the hospital viewport", async ({ page }) => {
    await importAssetsAndEnterPlayableShell(page);
    await page.getByTestId("pause-toggle").click();
    await page.getByTestId("playfield").focus();
    await expect(page.getByTestId("hospital-canvas-summary")).toContainText("zoom 100%");
    await page.keyboard.press("Equal");
    await expect(page.getByTestId("hospital-canvas-summary")).toContainText("zoom 150%");
    await expect(page.getByTestId("action-status")).toHaveText("Action: zoom 150%");
    await page.keyboard.press("Shift+Equal");
    await expect(page.getByTestId("hospital-canvas-summary")).toContainText("zoom 200%");
    await expect(page.getByTestId("action-status")).toHaveText("Action: zoom 200%");
    await page.keyboard.press("Minus");
    await expect(page.getByTestId("hospital-canvas-summary")).toContainText("zoom 150%");
    await page.keyboard.press("Shift+Minus");
    await expect(page.getByTestId("hospital-canvas-summary")).toContainText("zoom 75%");
    await page.keyboard.press("Digit0");
    await expect(page.getByTestId("hospital-canvas-summary")).toContainText("zoom 100%");
    await expect(page.getByTestId("action-status")).toHaveText("Action: zoom 100%");
});
test("phase 7 keyboard shortcuts control original transparent wall mode", async ({ page }) => {
    await importAssetsAndEnterPlayableShell(page);
    await page.getByTestId("pause-toggle").click();
    await page.getByTestId("playfield").focus();
    await expect(page.getByTestId("hospital-canvas-summary")).toContainText("transparent walls no");
    await page.keyboard.down("KeyX");
    await expect(page.getByTestId("hospital-canvas-summary")).toContainText("transparent walls yes");
    await expect(page.getByTestId("action-status")).toHaveText("Action: transparent walls held");
    await page.keyboard.up("KeyX");
    await expect(page.getByTestId("hospital-canvas-summary")).toContainText("transparent walls no");
    await expect(page.getByTestId("action-status")).toHaveText("Action: transparent walls released");
    await page.keyboard.press("Shift+KeyX");
    await expect(page.getByTestId("hospital-canvas-summary")).toContainText("transparent walls yes");
    await expect(page.getByTestId("action-status")).toHaveText("Action: transparent walls shown");
    await page.keyboard.press("Shift+KeyX");
    await expect(page.getByTestId("hospital-canvas-summary")).toContainText("transparent walls no");
    await expect(page.getByTestId("action-status")).toHaveText("Action: transparent walls hidden");
});
test("phase 7 keyboard shortcuts store and recall original camera positions", async ({ page }) => {
    await importAssetsAndEnterPlayableShell(page);
    await page.getByTestId("pause-toggle").click();
    await page.getByTestId("playfield").focus();
    await page.keyboard.press("Control+Digit9");
    await expect(page.getByTestId("action-status")).toHaveText("Action: camera position 9 empty");
    const initialSummary = (await page.getByTestId("hospital-canvas-summary").textContent()) ?? "";
    await page.keyboard.press("Alt+Digit1");
    await expect(page.getByTestId("action-status")).toHaveText("Action: camera position 1 stored");
    await page.keyboard.press("ArrowRight");
    await page.keyboard.press("ArrowDown");
    await page.keyboard.press("Equal");
    await expect(page.getByTestId("hospital-canvas-summary")).toContainText("zoom 150%");
    expect((await page.getByTestId("hospital-canvas-summary").textContent()) ?? "").not.toBe(initialSummary);
    await page.keyboard.press("Control+Digit1");
    await expect(page.getByTestId("action-status")).toHaveText("Action: camera position 1 recalled");
    await expect(page.getByTestId("hospital-canvas-summary")).toHaveText(initialSummary);
    await page.keyboard.press("Alt+Digit0");
    await expect(page.getByTestId("action-status")).toHaveText("Action: camera position 0 stored");
    await page.keyboard.press("Control+Digit0");
    await expect(page.getByTestId("action-status")).toHaveText("Action: camera position 0 recalled");
});
test("phase 7 keyboard shortcuts save and load active slot", async ({ page }) => {
    await importAssetsAndEnterPlayableShell(page);
    await page.getByTestId("pause-toggle").click();
    await page.getByTestId("save-slot-name").fill("keyboard-save-load");
    await page.keyboard.press("Equal");
    await expect(page.getByTestId("save-slot-name")).toHaveValue("keyboard-save-load=");
    await page.getByTestId("save-slot-name").fill("keyboard-save-load");
    await page.keyboard.press("Minus");
    await expect(page.getByTestId("save-slot-name")).toHaveValue("keyboard-save-load-");
    await page.getByTestId("save-slot-name").fill("keyboard-save-load");
    await page.keyboard.press("Digit0");
    await expect(page.getByTestId("save-slot-name")).toHaveValue("keyboard-save-load0");
    await page.getByTestId("save-slot-name").fill("keyboard-save-load");
    await page.keyboard.press("KeyX");
    await expect(page.getByTestId("save-slot-name")).toHaveValue("keyboard-save-loadx");
    await page.getByTestId("save-slot-name").fill("keyboard-save-load");
    await page.keyboard.press("KeyC");
    await expect(page.getByTestId("save-slot-name")).toHaveValue("keyboard-save-loadc");
    await page.getByTestId("save-slot-name").fill("keyboard-save-load");
    await page.keyboard.press("Shift+KeyC");
    await expect(page.getByTestId("save-slot-name")).toHaveValue("keyboard-save-loadC");
    await page.getByTestId("save-slot-name").fill("keyboard-save-load");
    await page.keyboard.press("Shift+KeyA");
    await expect(page.getByTestId("save-slot-name")).toHaveValue("keyboard-save-loadA");
    await page.getByTestId("save-slot-name").fill("keyboard-save-load");
    await page.keyboard.press("Shift+KeyQ");
    await expect(page.getByTestId("save-slot-name")).toHaveValue("keyboard-save-loadQ");
    await page.getByTestId("save-slot-name").fill("keyboard-save-load");
    await page.keyboard.press("Alt+KeyA");
    await expect(page.locator(":focus")).toHaveAttribute("data-testid", "save-slot-name");
    await page.keyboard.press("F1");
    await expect(page.locator(":focus")).toHaveAttribute("data-testid", "save-slot-name");
    await page.keyboard.press("F2");
    await expect(page.locator(":focus")).toHaveAttribute("data-testid", "save-slot-name");
    await page.keyboard.press("F3");
    await expect(page.locator(":focus")).toHaveAttribute("data-testid", "save-slot-name");
    await page.keyboard.press("F4");
    await expect(page.locator(":focus")).toHaveAttribute("data-testid", "save-slot-name");
    await page.keyboard.press("F5");
    await expect(page.locator(":focus")).toHaveAttribute("data-testid", "save-slot-name");
    await page.keyboard.press("F7");
    await expect(page.locator(":focus")).toHaveAttribute("data-testid", "save-slot-name");
    await page.keyboard.press("F8");
    await expect(page.locator(":focus")).toHaveAttribute("data-testid", "save-slot-name");
    await page.keyboard.press("F9");
    await expect(page.locator(":focus")).toHaveAttribute("data-testid", "save-slot-name");
    await page.keyboard.press("F10");
    await expect(page.locator(":focus")).toHaveAttribute("data-testid", "save-slot-name");
    await page.keyboard.press("KeyB");
    await expect(page.getByTestId("save-slot-name")).toHaveValue("keyboard-save-loadb");
    await page.getByTestId("save-slot-name").fill("keyboard-save-load");
    await page.keyboard.press("KeyR");
    await expect(page.getByTestId("save-slot-name")).toHaveValue("keyboard-save-loadr");
    await page.getByTestId("save-slot-name").fill("keyboard-save-load");
    await page.keyboard.press("KeyM");
    await expect(page.getByTestId("save-slot-name")).toHaveValue("keyboard-save-loadm");
    await page.getByTestId("save-slot-name").fill("keyboard-save-load");
    await page.keyboard.press("KeyJ");
    await expect(page.getByTestId("save-slot-name")).toHaveValue("keyboard-save-loadj");
    await page.getByTestId("save-slot-name").fill("keyboard-save-load");
    await page.keyboard.press("KeyI");
    await expect(page.getByTestId("save-slot-name")).toHaveValue("keyboard-save-loadi");
    await page.getByTestId("save-slot-name").fill("keyboard-save-load");
    await page.keyboard.press("KeyT");
    await expect(page.getByTestId("save-slot-name")).toHaveValue("keyboard-save-loadt");
    await page.getByTestId("save-slot-name").fill("keyboard-save-load");
    await page.keyboard.press("KeyG");
    await expect(page.getByTestId("save-slot-name")).toHaveValue("keyboard-save-loadg");
    await page.getByTestId("save-slot-name").fill("keyboard-save-load");
    await page.keyboard.press("KeyV");
    await expect(page.getByTestId("save-slot-name")).toHaveValue("keyboard-save-loadv");
    await page.getByTestId("save-slot-name").fill("keyboard-save-load");
    await page.getByTestId("playfield").focus();
    await page.keyboard.press("KeyB");
    await expect(page.locator(":focus")).toHaveAttribute("data-testid", "hire-diagnostician");
    await expect(page.getByTestId("hospital-placement-mode")).toHaveText("Placement: none");
    await page.getByTestId("playfield").focus();
    await expect(page.getByTestId("advisor-status")).toBeVisible();
    await page.keyboard.press("Shift+KeyA");
    await expect(page.getByTestId("advisor-status")).toBeHidden();
    await expect(page.getByTestId("action-status")).toHaveText("Action: advisor hidden");
    await page.keyboard.press("Shift+KeyA");
    await expect(page.getByTestId("advisor-status")).toBeVisible();
    await expect(page.getByTestId("action-status")).toHaveText("Action: advisor shown");
    await expect(page.getByTestId("event-count")).toBeVisible();
    await expect(page.getByTestId("last-event")).toBeVisible();
    await expect(page.getByTestId("recent-events")).toBeVisible();
    await page.keyboard.press("Alt+KeyA");
    await expect(page.getByTestId("event-count")).toBeHidden();
    await expect(page.getByTestId("last-event")).toBeHidden();
    await expect(page.getByTestId("recent-events")).toBeHidden();
    await expect(page.getByTestId("action-status")).toHaveText("Action: announcements hidden");
    await page.keyboard.press("Alt+KeyA");
    await expect(page.getByTestId("event-count")).toBeVisible();
    await expect(page.getByTestId("last-event")).toBeVisible();
    await expect(page.getByTestId("recent-events")).toBeVisible();
    await expect(page.getByTestId("action-status")).toHaveText("Action: announcements shown");
    await page.getByTestId("playfield").focus();
    const cashBeforeInformationToggle = (await page.getByTestId("cash").textContent()) ?? "";
    const selectionBeforeInformationToggle = (await page.getByTestId("selection-status").textContent()) ?? "";
    await page.keyboard.press("KeyI");
    await expect(page.locator(":focus")).toHaveAttribute("data-testid", "information-status");
    await expect(page.getByTestId("information-status")).toHaveText("Info: shown");
    await expect(page.getByTestId("action-status")).toHaveText("Action: information shown");
    await expect(page.getByTestId("cash")).toHaveText(cashBeforeInformationToggle);
    await expect(page.getByTestId("selection-status")).toHaveText(selectionBeforeInformationToggle);
    await page.getByTestId("playfield").focus();
    await page.keyboard.press("KeyI");
    await expect(page.locator(":focus")).toHaveAttribute("data-testid", "information-status");
    await expect(page.getByTestId("information-status")).toHaveText("Info: hidden");
    await expect(page.getByTestId("action-status")).toHaveText("Action: information hidden");
    await page.getByTestId("playfield").focus();
    const cashBeforeMenuBar = (await page.getByTestId("cash").textContent()) ?? "";
    await expect(page.getByTestId("game-menu-bar")).toBeHidden();
    await page.keyboard.press("Escape");
    await expect(page.getByTestId("game-menu-bar")).toBeVisible();
    await expect(page.locator(":focus")).toHaveAttribute("data-testid", "game-menu-file");
    await expect(page.getByTestId("action-status")).toHaveText("Action: menu bar shown");
    await expect(page.getByTestId("cash")).toHaveText(cashBeforeMenuBar);
    await page.getByTestId("playfield").focus();
    const cashBeforeBankManager = (await page.getByTestId("cash").textContent()) ?? "";
    const loanStatusBeforeBankManager = (await page.getByTestId("loan-status").textContent()) ?? "";
    await page.keyboard.press("F1");
    await expect(page.getByTestId("bank-manager-panel")).toBeVisible();
    await expect(page.locator(":focus")).toHaveAttribute("data-testid", "bank-manager-take-loan");
    await expect(page.getByTestId("bank-manager-loan")).toHaveText(loanStatusBeforeBankManager);
    await expect(page.getByTestId("bank-manager-interest")).toHaveText(await page.getByTestId("loan-interest").textContent() ?? "");
    await expect(page.getByTestId("bank-manager-cashflow")).toHaveText(await page.getByTestId("cashflow-net").textContent() ?? "");
    await page.getByTestId("bank-manager-take-loan").click();
    await expect(page.getByTestId("bank-manager-loan")).toHaveText("Loan: 5000/20000, chunk 5000, available 5000, repay 5000");
    await page.getByTestId("bank-manager-repay-loan").click();
    await expect(page.getByTestId("bank-manager-loan")).toHaveText("Loan: 0/20000, chunk 5000, available 5000, repay 0");
    await expect(page.getByTestId("cash")).toHaveText(cashBeforeBankManager);
    await page.keyboard.press("Escape");
    await expect(page.getByTestId("bank-manager-panel")).toBeHidden();
    await expect(page.getByTestId("action-status")).toHaveText("Action: bank manager closed");
    await page.getByTestId("playfield").focus();
    const cashBeforeBankStats = (await page.getByTestId("cash").textContent()) ?? "";
    const financeLedgerBeforeBankStats = (await page.getByTestId("finance-ledger").textContent()) ?? "";
    await page.keyboard.press("F2");
    await expect(page.getByTestId("bank-stats-panel")).toBeVisible();
    await expect(page.locator(":focus")).toHaveAttribute("data-testid", "bank-stats-close");
    await expect(page.getByTestId("bank-stats-ledger")).toHaveText(financeLedgerBeforeBankStats);
    await expect(page.getByTestId("bank-stats-audit")).toHaveText(await page.getByTestId("finance-audit").textContent() ?? "");
    await expect(page.getByTestId("bank-stats-cashflow")).toHaveText(await page.getByTestId("cashflow-net").textContent() ?? "");
    await expect(page.getByTestId("bank-stats-run-audit")).toBeDisabled();
    await expect(page.getByTestId("cash")).toHaveText(cashBeforeBankStats);
    await page.getByTestId("bank-stats-close").click();
    await expect(page.getByTestId("bank-stats-panel")).toBeHidden();
    await expect(page.getByTestId("action-status")).toHaveText("Action: bank stats closed");
    await page.getByTestId("playfield").focus();
    const cashBeforeStaffPanel = (await page.getByTestId("cash").textContent()) ?? "";
    const activeStaffBeforePanel = (await page.getByTestId("active-staff").textContent()) ?? "";
    await page.keyboard.press("F3");
    await expect(page.getByTestId("staff-panel")).toBeVisible();
    await expect(page.locator(":focus")).toHaveAttribute("data-testid", "staff-panel-hire-diagnostician");
    await expect(page.getByTestId("staff-panel-active")).toHaveText(activeStaffBeforePanel);
    await expect(page.getByTestId("staff-panel-break")).toHaveText(await page.getByTestId("on-break-staff").textContent() ?? "");
    await expect(page.getByTestId("staff-panel-training")).toHaveText(await page.getByTestId("staff-training-status").textContent() ?? "");
    await expect(page.getByTestId("staff-panel-market")).toHaveText(await page.getByTestId("staff-market-status").textContent() ?? "");
    await expect(page.getByTestId("cash")).toHaveText(cashBeforeStaffPanel);
    await page.getByTestId("staff-panel-hire-nurse").click();
    await expect(page.getByTestId("staff-panel")).toBeHidden();
    await expect(page.getByTestId("hospital-placement-mode")).toHaveText("Placement: hire Nurse");
    await page.keyboard.press("Escape");
    await expect(page.getByTestId("hospital-placement-mode")).toHaveText("Placement: none");
    await page.getByTestId("playfield").focus();
    const cashBeforeFurnishFocus = (await page.getByTestId("cash").textContent()) ?? "";
    const actionStatusBeforeFurnishFocus = (await page.getByTestId("action-status").textContent()) ?? "";
    const objectAvailabilityBeforeFocus = (await page.getByTestId("object-availability").textContent()) ?? "";
    await page.keyboard.press("KeyG");
    await expect(page.locator(":focus")).toHaveAttribute("data-testid", "object-availability");
    await expect(page.getByTestId("cash")).toHaveText(cashBeforeFurnishFocus);
    await expect(page.getByTestId("action-status")).toHaveText(actionStatusBeforeFurnishFocus);
    await expect(page.getByTestId("object-availability")).toHaveText(objectAvailabilityBeforeFocus);
    await page.getByTestId("playfield").focus();
    const cashBeforeEditRoomFocus = (await page.getByTestId("cash").textContent()) ?? "";
    const actionStatusBeforeEditRoomFocus = (await page.getByTestId("action-status").textContent()) ?? "";
    const roomAvailabilityBeforeFocus = (await page.getByTestId("room-availability").textContent()) ?? "";
    await page.keyboard.press("KeyV");
    await expect(page.locator(":focus")).toHaveAttribute("data-testid", "room-availability");
    await expect(page.getByTestId("cash")).toHaveText(cashBeforeEditRoomFocus);
    await expect(page.getByTestId("action-status")).toHaveText(actionStatusBeforeEditRoomFocus);
    await expect(page.getByTestId("room-availability")).toHaveText(roomAvailabilityBeforeFocus);
    await page.getByTestId("playfield").focus();
    const mapBeforeFocus = (await page.getByTestId("hospital-map-select").inputValue()) ?? "";
    await page.keyboard.press("F4");
    await expect(page.getByTestId("town-map-panel")).toBeVisible();
    await expect(page.locator(":focus")).toHaveAttribute("data-testid", "town-map-panel-select");
    await expect(page.getByTestId("town-map-panel-select")).toHaveValue(mapBeforeFocus);
    await expect(page.getByTestId("town-map-panel-current")).toHaveText(`Map: ${mapBeforeFocus}`);
    await expect(page.getByTestId("town-map-panel-cash")).toHaveText(await page.getByTestId("cash").textContent() ?? "");
    await page.keyboard.press("Escape");
    await expect(page.getByTestId("town-map-panel")).toBeHidden();
    await expect(page.getByTestId("action-status")).toHaveText("Action: town map closed");
    await page.getByTestId("playfield").focus();
    await page.keyboard.press("KeyT");
    await expect(page.getByTestId("town-map-panel")).toBeVisible();
    await expect(page.locator(":focus")).toHaveAttribute("data-testid", "town-map-panel-select");
    await expect(page.getByTestId("hospital-map-select")).toHaveValue(mapBeforeFocus);
    await page.getByTestId("town-map-panel-close").click();
    await expect(page.getByTestId("town-map-panel")).toBeHidden();
    await page.getByTestId("playfield").focus();
    await page.keyboard.press("KeyC");
    await expect(page.getByTestId("casebook-panel")).toBeVisible();
    await expect(page.locator(":focus")).toHaveAttribute("data-testid", "casebook-panel-close");
    await expect(page.getByTestId("casebook-panel-summary")).toHaveText(await page.getByTestId("casebook-summary").textContent() ?? "");
    await page.keyboard.press("Escape");
    await expect(page.getByTestId("casebook-panel")).toBeHidden();
    await expect(page.getByTestId("action-status")).toHaveText("Action: casebook closed");
    await page.getByTestId("playfield").focus();
    await page.keyboard.press("Shift+KeyC");
    await expect(page.getByTestId("casebook-panel")).toBeVisible();
    await expect(page.locator(":focus")).toHaveAttribute("data-testid", "casebook-panel-close");
    await page.getByTestId("casebook-panel-close").click();
    await expect(page.getByTestId("casebook-panel")).toBeHidden();
    await page.getByTestId("playfield").focus();
    await page.keyboard.press("F5");
    await expect(page.getByTestId("casebook-panel")).toBeVisible();
    await expect(page.locator(":focus")).toHaveAttribute("data-testid", "casebook-panel-close");
    await page.keyboard.press("Escape");
    await expect(page.getByTestId("casebook-panel")).toBeHidden();
    await page.getByTestId("playfield").focus();
    const cashBeforeResearchPanel = (await page.getByTestId("cash").textContent()) ?? "";
    const researchStatusBeforePanel = (await page.getByTestId("research-status").textContent()) ?? "";
    await page.keyboard.press("F6");
    await expect(page.getByTestId("research-panel")).toBeVisible();
    await expect(page.locator(":focus")).toHaveAttribute("data-testid", "research-panel-start");
    await expect(page.getByTestId("research-panel-status")).toHaveText(researchStatusBeforePanel);
    await expect(page.getByTestId("research-panel-effect")).toHaveText(await page.getByTestId("research-effect").textContent() ?? "");
    await expect(page.getByTestId("research-panel-expertise")).toHaveText(await page.getByTestId("scenario-expertise").textContent() ?? "");
    await expect(page.getByTestId("cash")).toHaveText(cashBeforeResearchPanel);
    await page.getByTestId("research-panel-close").click();
    await expect(page.getByTestId("research-panel")).toBeHidden();
    await expect(page.getByTestId("action-status")).toHaveText("Action: research panel closed");
    await page.getByTestId("playfield").focus();
    await page.keyboard.press("KeyR");
    await expect(page.getByTestId("research-panel")).toBeVisible();
    await expect(page.getByTestId("research-panel-status")).toHaveText(researchStatusBeforePanel);
    await expect(page.getByTestId("cash")).toHaveText(cashBeforeResearchPanel);
    await page.keyboard.press("Escape");
    await expect(page.getByTestId("research-panel")).toBeHidden();
    await expect(page.getByTestId("action-status")).toHaveText("Action: research panel closed");
    await page.getByTestId("playfield").focus();
    const cashBeforeStatusPanel = (await page.getByTestId("cash").textContent()) ?? "";
    const levelObjectiveStatusBeforePanel = (await page.getByTestId("level-objective-status").textContent()) ?? "";
    const levelObjectiveProgressBeforePanel = (await page.getByTestId("level-objective-progress").textContent()) ?? "";
    const levelObjectiveSafetyBeforePanel = (await page.getByTestId("level-objective-safety").textContent()) ?? "";
    const hospitalRatingBeforePanel = (await page.getByTestId("hospital-rating").textContent()) ?? "";
    const hospitalAwardsBeforePanel = (await page.getByTestId("hospital-awards").textContent()) ?? "";
    await page.keyboard.press("F7");
    await expect(page.getByTestId("status-panel")).toBeVisible();
    await expect(page.locator(":focus")).toHaveAttribute("data-testid", "status-panel-close");
    await expect(page.getByTestId("status-panel-objective-status")).toHaveText(levelObjectiveStatusBeforePanel);
    await expect(page.getByTestId("status-panel-objective-progress")).toHaveText(levelObjectiveProgressBeforePanel);
    await expect(page.getByTestId("status-panel-objective-safety")).toHaveText(levelObjectiveSafetyBeforePanel);
    await expect(page.getByTestId("status-panel-rating")).toHaveText(hospitalRatingBeforePanel);
    await expect(page.getByTestId("status-panel-awards")).toHaveText(hospitalAwardsBeforePanel);
    await expect(page.getByTestId("cash")).toHaveText(cashBeforeStatusPanel);
    await expect(page.getByTestId("action-status")).toHaveText("Action: status panel opened");
    await page.keyboard.press("Escape");
    await expect(page.getByTestId("status-panel")).toBeHidden();
    await expect(page.getByTestId("action-status")).toHaveText("Action: status panel closed");
    await page.getByTestId("playfield").focus();
    const cashBeforeChartsPanel = (await page.getByTestId("cash").textContent()) ?? "";
    const reputationBeforeChartsPanel = (await page.getByTestId("reputation").textContent()) ?? "";
    const cashflowNetBeforeChartsPanel = (await page.getByTestId("cashflow-net").textContent()) ?? "";
    const cumulativeCashflowBeforeChartsPanel = (await page.getByTestId("cashflow-cumulative").textContent()) ?? "";
    const loanBeforeChartsPanel = (await page.getByTestId("loan-status").textContent()) ?? "";
    const ledgerBeforeChartsPanel = (await page.getByTestId("finance-ledger").textContent()) ?? "";
    await page.keyboard.press("F8");
    await expect(page.getByTestId("charts-panel")).toBeVisible();
    await expect(page.locator(":focus")).toHaveAttribute("data-testid", "charts-panel-close");
    await expect(page.getByTestId("charts-panel-cash")).toHaveText(cashBeforeChartsPanel);
    await expect(page.getByTestId("charts-panel-reputation")).toHaveText(reputationBeforeChartsPanel);
    await expect(page.getByTestId("charts-panel-cashflow")).toHaveText(cashflowNetBeforeChartsPanel);
    await expect(page.getByTestId("charts-panel-cumulative")).toHaveText(cumulativeCashflowBeforeChartsPanel);
    await expect(page.getByTestId("charts-panel-loan")).toHaveText(loanBeforeChartsPanel);
    await expect(page.getByTestId("charts-panel-ledger")).toHaveText(ledgerBeforeChartsPanel);
    await expect(page.getByTestId("cash")).toHaveText(cashBeforeChartsPanel);
    await expect(page.getByTestId("action-status")).toHaveText("Action: charts panel opened");
    await page.keyboard.press("Escape");
    await expect(page.getByTestId("charts-panel")).toBeHidden();
    await expect(page.getByTestId("action-status")).toHaveText("Action: charts panel closed");
    await page.getByTestId("playfield").focus();
    const admissionsBeforePolicyPanel = (await page.getByTestId("admissions-status").textContent()) ?? "";
    const admissionPolicyBeforePanel = (await page.getByTestId("admission-policy-status").textContent()) ?? "";
    const pricingPolicyBeforePanel = (await page.getByTestId("pricing-policy-status").textContent()) ?? "";
    const admissionRulesBeforePolicyPanel = (await page.getByTestId("admission-rules").textContent()) ?? "";
    const routingRulesBeforePolicyPanel = (await page.getByTestId("routing-rules").textContent()) ?? "";
    await page.keyboard.press("F9");
    await expect(page.getByTestId("policy-panel")).toBeVisible();
    await expect(page.locator(":focus")).toHaveAttribute("data-testid", "policy-panel-admission-policy");
    await expect(page.getByTestId("policy-panel-admissions")).toHaveText(admissionsBeforePolicyPanel);
    await expect(page.getByTestId("policy-panel-admission-status")).toHaveText(admissionPolicyBeforePanel);
    await expect(page.getByTestId("policy-panel-pricing-status")).toHaveText(pricingPolicyBeforePanel);
    await expect(page.getByTestId("policy-panel-admission-rules")).toHaveText(admissionRulesBeforePolicyPanel);
    await expect(page.getByTestId("policy-panel-routing-rules")).toHaveText(routingRulesBeforePolicyPanel);
    await expect(page.getByTestId("policy-panel-admission-policy")).toHaveValue("standard");
    await expect(page.getByTestId("policy-panel-pricing-policy")).toHaveValue("standard");
    await expect(page.getByTestId("action-status")).toHaveText("Action: policy panel opened");
    await page.getByTestId("policy-panel-admission-policy").selectOption("aggressive");
    await expect(page.getByTestId("admission-policy")).toHaveValue("aggressive");
    await expect(page.getByTestId("policy-panel-admission-status")).toHaveText("Admission policy: aggressive");
    await expect(page.getByTestId("action-status")).toHaveText("Action: admission policy changed");
    await page.getByTestId("policy-panel-pricing-policy").selectOption("premium");
    await expect(page.getByTestId("pricing-policy")).toHaveValue("premium");
    await expect(page.getByTestId("policy-panel-pricing-status")).toHaveText("Pricing: premium, cash 135%, reputation -3/cure");
    await expect(page.getByTestId("action-status")).toHaveText("Action: pricing policy changed");
    await page.getByTestId("policy-panel-close").click();
    await expect(page.getByTestId("policy-panel")).toBeHidden();
    await expect(page.getByTestId("action-status")).toHaveText("Action: policy panel closed");
    await page.getByTestId("playfield").focus();
    const cashBeforeMachineMenu = (await page.getByTestId("cash").textContent()) ?? "";
    const roomsInMaintenanceBeforeMenu = (await page.getByTestId("rooms-in-maintenance").textContent()) ?? "";
    const maintenanceStaffBeforeMenu = (await page.getByTestId("maintenance-staff-status").textContent()) ?? "";
    const maintenanceStartsBeforeMenu = (await page.getByTestId("room-maintenance-start-events").textContent()) ?? "";
    const maintenanceCompletesBeforeMenu = (await page.getByTestId("room-maintenance-complete-events").textContent()) ?? "";
    const roomAvailabilityBeforeMenu = (await page.getByTestId("room-availability").textContent()) ?? "";
    const objectAvailabilityBeforeMenu = (await page.getByTestId("object-availability").textContent()) ?? "";
    await page.keyboard.press("F10");
    await expect(page.getByTestId("machine-menu-panel")).toBeVisible();
    await expect(page.locator(":focus")).toHaveAttribute("data-testid", "machine-menu-close");
    await expect(page.getByTestId("machine-menu-maintenance")).toHaveText(roomsInMaintenanceBeforeMenu);
    await expect(page.getByTestId("machine-menu-staff")).toHaveText(maintenanceStaffBeforeMenu);
    await expect(page.getByTestId("machine-menu-starts")).toHaveText(maintenanceStartsBeforeMenu);
    await expect(page.getByTestId("machine-menu-completes")).toHaveText(maintenanceCompletesBeforeMenu);
    await expect(page.getByTestId("machine-menu-rooms")).toHaveText(roomAvailabilityBeforeMenu);
    await expect(page.getByTestId("machine-menu-objects")).toHaveText(objectAvailabilityBeforeMenu);
    await expect(page.getByTestId("machine-menu-repair-selected-room")).toBeDisabled();
    await expect(page.getByTestId("cash")).toHaveText(cashBeforeMachineMenu);
    await expect(page.getByTestId("action-status")).toHaveText("Action: machine menu opened");
    await page.keyboard.press("Escape");
    await expect(page.getByTestId("machine-menu-panel")).toBeHidden();
    await expect(page.getByTestId("action-status")).toHaveText("Action: machine menu closed");
    await page.getByTestId("playfield").focus();
    await page.keyboard.press("Shift+KeyS");
    await expect(page.getByTestId("save-status")).toContainText("keyboard-save-load");
    await page.keyboard.press("KeyA");
    await expect(page.getByTestId("waiting")).toHaveText("Waiting: 1");
    await page.getByTestId("playfield").focus();
    const cashBeforeMessageFocus = (await page.getByTestId("cash").textContent()) ?? "";
    const lastEventBeforeMessageFocus = (await page.getByTestId("last-event").textContent()) ?? "";
    await page.keyboard.press("KeyM");
    await expect(page.locator(":focus")).toHaveAttribute("data-testid", "last-event");
    await expect(page.getByTestId("cash")).toHaveText(cashBeforeMessageFocus);
    await expect(page.getByTestId("last-event")).toHaveText(lastEventBeforeMessageFocus);
    await expect(page.getByTestId("action-status")).toHaveText("Action: message opened");
    await page.getByTestId("playfield").focus();
    await page.keyboard.press("Shift+KeyL");
    await expect(page.getByTestId("save-status")).toContainText("Save: loaded tick");
    await expect(page.getByTestId("waiting")).toHaveText("Waiting: 0");
    await page.keyboard.press("Alt+Shift+KeyS");
    await expect(page.getByTestId("save-status")).toContainText("keyboard-save-load");
    await page.keyboard.press("KeyA");
    await expect(page.getByTestId("waiting")).toHaveText("Waiting: 1");
    await page.keyboard.press("Alt+Shift+KeyL");
    await expect(page.getByTestId("save-status")).toContainText("Save: loaded tick");
    await expect(page.getByTestId("waiting")).toHaveText("Waiting: 0");
    await page.getByTestId("playfield").focus();
    await expect(page.getByTestId("quit-level-confirmation")).toBeHidden();
    await page.keyboard.press("Shift+KeyQ");
    await expect(page.getByTestId("quit-level-confirmation")).toBeVisible();
    await expect(page.locator(":focus")).toHaveAttribute("data-testid", "quit-level-cancel");
    await expect(page.getByTestId("action-status")).toHaveText("Action: quit level confirmation");
    await page.keyboard.press("Escape");
    await expect(page.getByTestId("quit-level-confirmation")).toBeHidden();
    await expect(page.getByTestId("action-status")).toHaveText("Action: quit level cancelled");
    await page.keyboard.press("Shift+KeyQ");
    await expect(page.getByTestId("quit-level-confirmation")).toBeVisible();
    await page.getByTestId("quit-level-confirm").click();
    await expect(page.getByRole("heading", { name: "Phase 8 Asset Import" })).toBeVisible();
    await expect
        .poll(async () => page.evaluate(() => window.localStorage.getItem("corsixth.phase8.asset-import.v1") ?? ""))
        .toContain("\"contract\":\"phase8.asset-import.v1\"");
});

async function expectCanvasAlpha(page, testId) {
    await expect
        .poll(async () => page.getByTestId(testId).evaluate((canvas) => {
        const context = canvas.getContext("2d");
        if (!context) {
            return false;
        }
        const pixels = context.getImageData(0, 0, canvas.width, canvas.height).data;
        for (let index = 0; index < pixels.length; index += 4) {
            if (pixels[index + 3] !== 0) {
                return true;
            }
        }
        return false;
    }))
        .toBe(true);
}
