import { assertGameCommand, isGameCommand } from "../src/command-contract";
describe("command contract", () => {
    it("accepts valid commands", () => {
        expect(isGameCommand({ type: "tick", count: 1 })).toBe(true);
        expect(isGameCommand({ type: "admit-patient", severity: 2, position: { x: 0, y: 1 } })).toBe(true);
        expect(isGameCommand({ type: "schedule-admit-patient", delay: 3, severity: 1 })).toBe(true);
        expect(isGameCommand({ type: "treat-patient" })).toBe(true);
        expect(isGameCommand({ type: "treat-patient", patientId: 2 })).toBe(true);
        expect(isGameCommand({ type: "send-patient-home", patientId: 2 })).toBe(true);
        expect(isGameCommand({ type: "prioritize-patient", patientId: 2 })).toBe(true);
        expect(isGameCommand({ type: "give-patient-drink", patientId: 2 })).toBe(true);
        expect(isGameCommand({ type: "send-patient-toilet", patientId: 2 })).toBe(true);
        expect(isGameCommand({ type: "shoot-rat" })).toBe(true);
        expect(isGameCommand({ type: "shoot-rat", hit: false })).toBe(true);
        expect(isGameCommand({ type: "water-plant" })).toBe(true);
        expect(isGameCommand({ type: "water-plant", watered: false })).toBe(true);
        expect(isGameCommand({ type: "hire-staff", role: "diagnostician" })).toBe(true);
        expect(isGameCommand({ type: "hire-staff", role: "diagnostician", initialSpecialties: ["researcher"] })).toBe(true);
        expect(isGameCommand({ type: "hire-staff", role: "nurse", position: { x: 5, y: 6 } })).toBe(true);
        expect(isGameCommand({ type: "hire-staff", role: "nurse", initialSkillLevel: 3, position: { x: 5, y: 6 } })).toBe(true);
        expect(isGameCommand({ type: "hire-staff", role: "handyman", position: { x: 5, y: 6 } })).toBe(true);
        expect(isGameCommand({ type: "hire-staff", role: "receptionist", position: { x: 5, y: 6 } })).toBe(true);
        expect(isGameCommand({ type: "fire-staff", staffId: 4 })).toBe(true);
        expect(isGameCommand({ type: "move-staff", staffId: 4, position: { x: 5, y: 6 } })).toBe(true);
        expect(isGameCommand({ type: "set-staff-status", staffId: 1, status: "on-break" })).toBe(true);
        expect(isGameCommand({ type: "rest-staff", staffId: 1, restType: "sofa" })).toBe(true);
        expect(isGameCommand({ type: "rest-staff", staffId: 1, restType: "game" })).toBe(true);
        expect(isGameCommand({ type: "open-room", roomType: "diagnosis" })).toBe(true);
        expect(isGameCommand({ type: "open-room", roomType: "cardiogram", position: { x: 7, y: 8 } })).toBe(true);
        expect(isGameCommand({ type: "open-room", roomType: "scanner", position: { x: 7, y: 8 } })).toBe(true);
        expect(isGameCommand({ type: "open-room", roomType: "ultrascan", position: { x: 7, y: 8 } })).toBe(true);
        expect(isGameCommand({ type: "open-room", roomType: "blood-machine", position: { x: 7, y: 8 } })).toBe(true);
        expect(isGameCommand({ type: "open-room", roomType: "x-ray", position: { x: 7, y: 8 } })).toBe(true);
        expect(isGameCommand({ type: "open-room", roomType: "general-diagnosis", position: { x: 7, y: 8 } })).toBe(true);
        expect(isGameCommand({ type: "open-room", roomType: "treatment", position: { x: 7, y: 8 } })).toBe(true);
        expect(isGameCommand({ type: "open-room", roomType: "ward", position: { x: 7, y: 8 } })).toBe(true);
        expect(isGameCommand({ type: "open-room", roomType: "pharmacy", position: { x: 7, y: 8 } })).toBe(true);
        expect(isGameCommand({ type: "open-room", roomType: "operating-theatre", position: { x: 7, y: 8 } })).toBe(true);
        expect(isGameCommand({ type: "open-room", roomType: "specialist", position: { x: 7, y: 8 } })).toBe(true);
        expect(isGameCommand({ type: "open-room", roomType: "psychiatry", position: { x: 7, y: 8 } })).toBe(true);
        expect(isGameCommand({ type: "open-room", roomType: "staff-room", position: { x: 7, y: 8 } })).toBe(true);
        expect(isGameCommand({ type: "open-room", roomType: "research", position: { x: 7, y: 8 } })).toBe(true);
        expect(isGameCommand({ type: "open-room", roomType: "toilets", position: { x: 7, y: 8 } })).toBe(true);
        expect(isGameCommand({ type: "open-room", roomType: "training-room", position: { x: 7, y: 8 } })).toBe(true);
        expect(isGameCommand({ type: "open-room", roomType: "inflation-room", position: { x: 7, y: 8 } })).toBe(true);
        expect(isGameCommand({ type: "open-room", roomType: "slack-tongue-clinic", position: { x: 7, y: 8 } })).toBe(true);
        expect(isGameCommand({ type: "open-room", roomType: "fracture-clinic", position: { x: 7, y: 8 } })).toBe(true);
        expect(isGameCommand({ type: "open-room", roomType: "hair-restoration", position: { x: 7, y: 8 } })).toBe(true);
        expect(isGameCommand({ type: "open-room", roomType: "jelly-vat", position: { x: 7, y: 8 } })).toBe(true);
        expect(isGameCommand({ type: "open-room", roomType: "decontamination", position: { x: 7, y: 8 } })).toBe(true);
        expect(isGameCommand({ type: "open-room", roomType: "electrolysis", position: { x: 7, y: 8 } })).toBe(true);
        expect(isGameCommand({ type: "open-room", roomType: "dna-fixer", position: { x: 7, y: 8 } })).toBe(true);
        expect(isGameCommand({ type: "place-object", objectIndex: 2, name: "Bench", cost: 50, strength: 12, orientation: "east", position: { x: 7, y: 8 } })).toBe(true);
        expect(isGameCommand({ type: "remove-object", objectId: 3 })).toBe(true);
        expect(isGameCommand({ type: "remove-room", roomId: 3 })).toBe(true);
        expect(isGameCommand({ type: "set-room-status", roomId: 2, status: "closed" })).toBe(true);
        expect(isGameCommand({ type: "repair-room", roomId: 2 })).toBe(true);
        expect(isGameCommand({ type: "set-pricing-policy", policy: "premium" })).toBe(true);
        expect(isGameCommand({ type: "take-loan" })).toBe(true);
        expect(isGameCommand({ type: "repay-loan" })).toBe(true);
        expect(isGameCommand({ type: "run-finance-audit" })).toBe(true);
        expect(isGameCommand({ type: "run-marketing-campaign" })).toBe(true);
        expect(isGameCommand({ type: "start-insurance-contract" })).toBe(true);
        expect(isGameCommand({ type: "run-awards-ceremony" })).toBe(true);
        expect(isGameCommand({ type: "run-awards-ceremony", cashReward: -3000, reputationReward: -5 })).toBe(true);
        expect(isGameCommand({ type: "start-research" })).toBe(true);
        expect(isGameCommand({ type: "start-emergency-wave" })).toBe(true);
        expect(isGameCommand({ type: "start-emergency-wave", emergencyIndex: 1 })).toBe(true);
        expect(isGameCommand({ type: "start-epidemic-outbreak" })).toBe(true);
        expect(isGameCommand({ type: "apply-earthquake", severity: 6, quakeIndex: 1 })).toBe(true);
        expect(isGameCommand({ type: "apply-alien-abduction", abductionIndex: 1 })).toBe(true);
        expect(isGameCommand({ type: "apply-alien-abduction", patientId: 2, abductionIndex: 1 })).toBe(true);
        expect(isGameCommand({ type: "train-staff", staffId: 1 })).toBe(true);
        expect(isGameCommand({ type: "start-vip-inspection" })).toBe(true);
    });
    it("rejects invalid commands", () => {
        expect(isGameCommand({ type: "tick", count: 0 })).toBe(false);
        expect(isGameCommand({ type: "admit-patient", severity: 5 })).toBe(false);
        expect(isGameCommand({ type: "admit-patient", severity: 2, position: { x: -1, y: 1 } })).toBe(false);
        expect(isGameCommand({ type: "schedule-admit-patient", delay: 0, severity: 2 })).toBe(false);
        expect(isGameCommand({ type: "treat-patient", patientId: 0 })).toBe(false);
        expect(isGameCommand({ type: "send-patient-home", patientId: 0 })).toBe(false);
        expect(isGameCommand({ type: "prioritize-patient", patientId: 0 })).toBe(false);
        expect(isGameCommand({ type: "give-patient-drink", patientId: 0 })).toBe(false);
        expect(isGameCommand({ type: "send-patient-toilet", patientId: 0 })).toBe(false);
        expect(isGameCommand({ type: "shoot-rat", hit: 1 })).toBe(false);
        expect(isGameCommand({ type: "water-plant", watered: 1 })).toBe(false);
        expect(isGameCommand({ type: "hire-staff", role: "surgeon" })).toBe(false);
        expect(isGameCommand({ type: "hire-staff", role: "nurse", position: { x: 1, y: -2 } })).toBe(false);
        expect(isGameCommand({ type: "hire-staff", role: "nurse", initialSkillLevel: 4 })).toBe(false);
        expect(isGameCommand({ type: "hire-staff", role: "diagnostician", initialSpecialties: ["admin"] })).toBe(false);
        expect(isGameCommand({ type: "fire-staff", staffId: 0 })).toBe(false);
        expect(isGameCommand({ type: "move-staff", staffId: 4, position: { x: -1, y: 6 } })).toBe(false);
        expect(isGameCommand({ type: "move-staff", staffId: 0, position: { x: 5, y: 6 } })).toBe(false);
        expect(isGameCommand({ type: "set-staff-status", staffId: 0, status: "on-break" })).toBe(false);
        expect(isGameCommand({ type: "rest-staff", staffId: 0, restType: "sofa" })).toBe(false);
        expect(isGameCommand({ type: "rest-staff", staffId: 1, restType: "bench" })).toBe(false);
        expect(isGameCommand({ type: "open-room", roomType: "chapel" })).toBe(false);
        expect(isGameCommand({ type: "open-room", roomType: "diagnosis", position: { x: -1, y: 0 } })).toBe(false);
        expect(isGameCommand({ type: "place-object", objectIndex: 2 })).toBe(false);
        expect(isGameCommand({ type: "place-object", objectIndex: 2, orientation: "diagonal", position: { x: 7, y: 8 } })).toBe(false);
        expect(isGameCommand({ type: "place-object", objectIndex: 2, strength: -1, position: { x: 7, y: 8 } })).toBe(false);
        expect(isGameCommand({ type: "remove-object", objectId: 0 })).toBe(false);
        expect(isGameCommand({ type: "remove-room", roomId: 0 })).toBe(false);
        expect(isGameCommand({ type: "set-room-status", roomId: 3, status: "offline" })).toBe(false);
        expect(isGameCommand({ type: "repair-room", roomId: 0 })).toBe(false);
        expect(isGameCommand({ type: "set-pricing-policy", policy: "free" })).toBe(false);
        expect(isGameCommand({ type: "run-awards-ceremony", cashReward: 1.5 })).toBe(false);
        expect(isGameCommand({ type: "apply-earthquake", severity: 0 })).toBe(false);
        expect(isGameCommand({ type: "apply-earthquake", severity: 100 })).toBe(false);
        expect(isGameCommand({ type: "apply-alien-abduction", patientId: 0 })).toBe(false);
        expect(isGameCommand({ type: "apply-alien-abduction", abductionIndex: -1 })).toBe(false);
        expect(isGameCommand({ type: "train-staff", staffId: 0 })).toBe(false);
        expect(isGameCommand({ type: "unknown" })).toBe(false);
    });
    it("throws on assertion failures", () => {
        expect(() => assertGameCommand({ type: "tick", count: -1 })).toThrow(/Invalid game command/);
    });
});
